class PalmInterpreter:
    """
    Generates dynamic palmistry interpretation from:
    - geometric palm features
    - RuleEngine output
    - classified palm lines

    This is a symbolic/palmistry interpretation layer.
    It does not claim medical or scientific prediction.
    """

    @staticmethod
    def _safe_float(value, default=0.0):
        try:
            return float(value)
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _line_stats(lines):
        """
        Calculate useful statistics from detected line segments.
        """

        if not lines:
            return {
                "count": 0,
                "average_length": 0.0,
                "total_length": 0.0
            }

        total_length = 0.0

        for line in lines:
            x1 = PalmInterpreter._safe_float(line.get("x1"))
            y1 = PalmInterpreter._safe_float(line.get("y1"))
            x2 = PalmInterpreter._safe_float(line.get("x2"))
            y2 = PalmInterpreter._safe_float(line.get("y2"))

            length = (
                (x2 - x1) ** 2 +
                (y2 - y1) ** 2
            ) ** 0.5

            total_length += length

        count = len(lines)

        return {
            "count": count,
            "average_length": round(total_length / count, 2),
            "total_length": round(total_length, 2)
        }

    @staticmethod
    def interpret(
        features,
        classified_lines,
        rule_based=None,
        palmistry_features=None
    ):
        """
        Generate a dynamic interpretation.

        Parameters
        ----------
        features:
            Geometric features extracted from MediaPipe landmarks.

        classified_lines:
            Palm lines classified into heart/head/life/fate.

        rule_based:
            Output generated by RuleEngine.

        palmistry_features:
            Optional detections from the trained palmistry YOLO model.
        """

        if not isinstance(features, dict):
            features = {}

        if not isinstance(classified_lines, dict):
            classified_lines = {}

        if not isinstance(rule_based, dict):
            rule_based = {}

        if not isinstance(palmistry_features, list):
            palmistry_features = []

        report = {}

        # =========================================================
        # GEOMETRIC FEATURES
        # =========================================================

        palm_width = PalmInterpreter._safe_float(
            features.get("palm_width")
        )

        palm_height = PalmInterpreter._safe_float(
            features.get("palm_height")
        )

        aspect_ratio = PalmInterpreter._safe_float(
            features.get("aspect_ratio")
        )

        thumb_length = PalmInterpreter._safe_float(
            features.get("thumb_length")
        )

        index_length = PalmInterpreter._safe_float(
            features.get("index_length")
        )

        middle_length = PalmInterpreter._safe_float(
            features.get("middle_length")
        )

        ring_length = PalmInterpreter._safe_float(
            features.get("ring_length")
        )

        pinky_length = PalmInterpreter._safe_float(
            features.get("pinky_length")
        )

        # =========================================================
        # RULE ENGINE VALUES
        # =========================================================

        palm_shape = rule_based.get(
            "palm_shape",
            "Unknown"
        )

        dominant_finger = rule_based.get(
            "dominant_finger",
            "Unknown"
        )

        palm_size = rule_based.get(
            "palm_size",
            "Unknown"
        )

        # =========================================================
        # HEART LINE
        # =========================================================

        heart_lines = classified_lines.get(
            "heart_line",
            []
        )

        heart_stats = PalmInterpreter._line_stats(
            heart_lines
        )

        heart_count = heart_stats["count"]
        heart_avg_length = heart_stats["average_length"]

        if heart_count == 0:

            report["love"] = (
                "The heart line was not clearly detected, "
                "so relationship interpretation is limited."
            )

        elif heart_count >= 10:

            report["love"] = (
                f"A strongly segmented heart-line pattern was detected "
                f"({heart_count} segments). This suggests an emotionally "
                f"expressive and relationship-focused symbolic pattern."
            )

        elif heart_avg_length >= 100:

            report["love"] = (
                f"The detected heart-line segments have relatively strong "
                f"average length ({heart_avg_length:.1f}). This indicates "
                f"a symbolic pattern associated with emotional consistency "
                f"and caring connections."
            )

        else:

            report["love"] = (
                f"The heart-line pattern contains {heart_count} detected "
                f"segments. This suggests a balanced emotional style with "
                f"attention to personal relationships."
            )

        # =========================================================
        # HEAD LINE
        # =========================================================

        head_lines = classified_lines.get(
            "head_line",
            []
        )

        head_stats = PalmInterpreter._line_stats(
            head_lines
        )

        head_count = head_stats["count"]
        head_avg_length = head_stats["average_length"]

        if head_count == 0:

            report["intelligence"] = (
                "The head line was not clearly detected, "
                "so the thinking-style interpretation is limited."
            )

        elif head_avg_length >= 100:

            report["intelligence"] = (
                f"The head-line pattern contains {head_count} detected "
                f"segments with an average length of "
                f"{head_avg_length:.1f}. Symbolically, this suggests "
                f"a focused and analytical thinking style."
            )

        elif head_count >= 10:

            report["intelligence"] = (
                f"The analysis detected {head_count} head-line segments. "
                f"This indicates an active and adaptable symbolic thinking "
                f"pattern."
            )

        else:

            report["intelligence"] = (
                f"The analysis detected {head_count} head-line segments. "
                f"This suggests a practical and balanced thinking style."
            )

        # =========================================================
        # LIFE LINE
        # =========================================================

        life_lines = classified_lines.get(
            "life_line",
            []
        )

        life_stats = PalmInterpreter._line_stats(
            life_lines
        )

        life_count = life_stats["count"]
        life_avg_length = life_stats["average_length"]

        if life_count == 0:

            report["health"] = (
                "The life line was not clearly detected. "
                "No symbolic vitality interpretation is available."
            )

        elif life_avg_length >= 100:

            report["health"] = (
                f"The life-line pattern contains {life_count} detected "
                f"segments with an average length of "
                f"{life_avg_length:.1f}. In palmistry symbolism, "
                f"this represents an energetic and active pattern."
            )

        elif life_count >= 10:

            report["health"] = (
                f"The analysis detected {life_count} life-line segments. "
                f"This represents a moderately active symbolic vitality "
                f"pattern."
            )

        else:

            report["health"] = (
                f"The analysis detected {life_count} life-line segments. "
                f"This represents a balanced symbolic vitality pattern."
            )

        # =========================================================
        # FATE LINE
        # =========================================================

        fate_lines = classified_lines.get(
            "fate_line",
            []
        )

        fate_stats = PalmInterpreter._line_stats(
            fate_lines
        )

        fate_count = fate_stats["count"]
        fate_avg_length = fate_stats["average_length"]

        if fate_count == 0:

            report["career"] = (
                "The fate-line pattern was not clearly detected. "
                "The symbolic career interpretation therefore suggests "
                "flexibility and possible changes in direction."
            )

        elif fate_avg_length >= 100:

            report["career"] = (
                f"The fate-line pattern contains {fate_count} detected "
                f"segments with an average length of "
                f"{fate_avg_length:.1f}. Symbolically, this suggests "
                f"a focused approach toward career and long-term goals."
            )

        elif fate_count >= 10:

            report["career"] = (
                f"The analysis detected {fate_count} fate-line segments. "
                f"This suggests an active career pattern with several "
                f"possible directions."
            )

        else:

            report["career"] = (
                f"The analysis detected {fate_count} fate-line segments. "
                f"This suggests a flexible career pattern."
            )

        # =========================================================
        # PERSONALITY
        # =========================================================

        if palm_shape == "Long Palm":

            personality = (
                "The measured palm proportions indicate a longer palm "
                "shape. In palmistry symbolism, this is associated with "
                "creative, intuitive, and adaptable characteristics."
            )

        elif palm_shape == "Wide Palm":

            personality = (
                "The measured palm proportions indicate a wider palm "
                "shape. In palmistry symbolism, this is associated with "
                "practical, energetic, and grounded characteristics."
            )

        elif palm_shape == "Balanced Palm":

            personality = (
                "The measured palm proportions indicate a balanced palm "
                "shape. In palmistry symbolism, this is associated with "
                "adaptability and a balanced approach to situations."
            )

        else:

            personality = (
                "The palm proportions were detected, but the symbolic "
                "palm shape could not be determined confidently."
            )

        report["personality"] = personality

        # =========================================================
        # DOMINANT FINGER
        # =========================================================

        report["dominant_finger"] = (
            f"The {dominant_finger} shows the largest measured "
            f"finger-to-wrist distance among the detected landmarks."
        )

        # =========================================================
        # PALM SIZE
        # =========================================================

        report["palm_size"] = (
            f"The measured palm width is {palm_width:.4f} and "
            f"palm height is {palm_height:.4f}. "
            f"The rule engine categorizes the palm as {palm_size}."
        )

        # =========================================================
        # PALM PROPORTION
        # =========================================================

        report["palm_proportion"] = (
            f"Palm aspect ratio: {aspect_ratio:.3f}. "
            f"Palm shape classification: {palm_shape}."
        )

        # =========================================================
        # FINGER MEASUREMENTS
        # =========================================================

        report["finger_analysis"] = (
            f"Thumb={thumb_length:.3f}, "
            f"Index={index_length:.3f}, "
            f"Middle={middle_length:.3f}, "
            f"Ring={ring_length:.3f}, "
            f"Pinky={pinky_length:.3f}."
        )

        # =========================================================
        # PALMISTRY MODEL FEATURES
        # =========================================================

        if palmistry_features:

            feature_names = []

            for item in palmistry_features:

                if not isinstance(item, dict):
                    continue

                name = item.get(
                    "class_name",
                    item.get("name", "Unknown")
                )

                confidence = PalmInterpreter._safe_float(
                    item.get("confidence")
                )

                feature_names.append(
                    f"{name} ({confidence:.2f})"
                )

            if feature_names:

                report["detected_features"] = (
                    "Trained palmistry model detections: "
                    + ", ".join(feature_names)
                )

            else:

                report["detected_features"] = (
                    "The trained palmistry model returned detections "
                    "without readable feature names."
                )

        else:

            report["detected_features"] = (
                "No trained palmistry feature was detected above "
                "the current confidence threshold for this image."
            )

        # =========================================================
        # LINE EVIDENCE
        # =========================================================

        report["line_evidence"] = (
            f"Heart={heart_count}, "
            f"Head={head_count}, "
            f"Life={life_count}, "
            f"Fate={fate_count}."
        )

        # =========================================================
        # SUMMARY
        # =========================================================

        report["summary"] = (
            f"Dynamic palm analysis: {palm_shape}, "
            f"{palm_size} palm, dominant {dominant_finger}. "
            f"Detected line segments — "
            f"Heart: {heart_count}, "
            f"Head: {head_count}, "
            f"Life: {life_count}, "
            f"Fate: {fate_count}."
        )

        return report